# Generated by Django 3.1.2 on 2020-10-28 11:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('modulos', '0006_aula_vimeo_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aula',
            name='vimeo_id',
            field=models.CharField(max_length=32),
        ),
    ]
